import { CardPatientProps } from "../components/organisms/CardPatient";

export const mockPatientsData: CardPatientProps[] = [{
   id: 1,
   fullName: "Nguyễn Văn A",
   img: "https://source.unsplash.com/random",
   age: 56,
   gender: "male",
   address: "Quận 10 - Thành phố Hồ Chí Minh",
   phone: "0906090909",
   email: "user@mail.com",
   status: "normal",
}, {
   id: 2,
   fullName: "Nguyễn Văn B",
   img: "https://source.unsplash.com/random",
   age: 56,
   gender: "male",
   address: "Quận 10 - Thành phố Hồ Chí Minh",
   phone: "0906090909",
   email: "user@mail.com",
   status: "light",
}, {
   id: 3,
   fullName: "Nguyễn Văn C",
   img: "https://source.unsplash.com/random",
   age: 33,
   gender: "male",
   address: "Quận 10 - Thành phố Hồ Chí Minh",
   phone: "0906090909",
   email: "user@mail.com",
   status: "heavy",
}, {
   id: 4,
   fullName: "Nguyễn Văn D",
   img: "https://source.unsplash.com/random",
   age: 56,
   gender: "male",
   address: "Quận 10 - Thành phố Hồ Chí Minh",
   phone: "0906090909",
   email: "user@mail.com",
   status: "normal",
}, {
   id: 5,
   fullName: "Nguyễn Văn E",
   img: "https://source.unsplash.com/random",
   age: 70,
   gender: "male",
   address: "Quận 10 - Thành phố Hồ Chí Minh",
   phone: "0906090909",
   email: "user@mail.com",
   status: "normal",
},
{
   id: 1,
   fullName: "Nguyễn Văn A",
   img: "https://source.unsplash.com/random",
   age: 56,
   gender: "male",
   address: "Quận 10 - Thành phố Hồ Chí Minh",
   phone: "0906090909",
   email: "user@mail.com",
   status: "normal",
}, {
   id: 2,
   fullName: "Nguyễn Văn B",
   img: "https://source.unsplash.com/random",
   age: 56,
   gender: "male",
   address: "Quận 10 - Thành phố Hồ Chí Minh",
   phone: "0906090909",
   email: "user@mail.com",
   status: "light",
}, {
   id: 3,
   fullName: "Nguyễn Văn C",
   img: "https://source.unsplash.com/random",
   age: 33,
   gender: "male",
   address: "Quận 10 - Thành phố Hồ Chí Minh",
   phone: "0906090909",
   email: "user@mail.com",
   status: "heavy",
}, {
   id: 4,
   fullName: "Nguyễn Văn D",
   img: "https://source.unsplash.com/random",
   age: 56,
   gender: "male",
   address: "Quận 10 - Thành phố Hồ Chí Minh",
   phone: "0906090909",
   email: "user@mail.com",
   status: "normal",
}, {
   id: 5,
   fullName: "Nguyễn Văn E",
   img: "https://source.unsplash.com/random",
   age: 70,
   gender: "male",
   address: "Quận 10 - Thành phố Hồ Chí Minh",
   phone: "0906090909",
   email: "user@mail.com",
   status: "normal",
}];
